server:
  port: 8081

spring:
  application:
    name: orderservice
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  base-path: /orderservice

logging:
  pattern:
    level: "%5p [${X-Correlation-ID:NA}]"